-- ===========================================================================
-- TOMBSTONE — DO NOT APPLY THIS FILE. IT NO LONGER CONTAINS SQL.
-- ===========================================================================
--
-- This file used to define semantic_search_memories over EIGHT tables with the
-- signature (vector, double precision, integer, text), and its own header said
-- "Identical to migrations/semantic-recall-all-tables.sql — apply either."
--
-- Both are gone as of 2026-08-22. Applying either one to a current database
-- would have caused:
--
--   * A SECOND OVERLOAD. The live function takes `real`, not `double
--     precision`/`FLOAT`. The DROP at the top of the old file named the wrong
--     signature and silently no-opped under IF EXISTS, then CREATE FUNCTION
--     added a second copy. PostgREST resolves rpc/ by name, so recall would
--     have stopped working entirely rather than degrading.
--   * SOFT-DELETED MEMORIES REAPPEARING. It had no
--     COALESCE(status,'active')='active' filter on any branch.
--   * NULL CONTENT. It read only the legacy column (description/detail/what/
--     reference/what_happened) where the live function reads
--     COALESCE(content, legacy).
--   * FOUR MISSING BRANCHES. It reached 8 tables; the deployed function reaches
--     12 — it omitted essence, reflections, session_logs and people.
--
-- ---------------------------------------------------------------------------
-- WHAT TO USE INSTEAD
-- ---------------------------------------------------------------------------
--
--   migrations/semantic-recall-canonical.sql
--
-- It is transcribed from pg_get_functiondef on the live database, drops
-- superseded overloads by argument type inside a transaction, and verifies
-- afterwards that exactly one function exists with the right signature over
-- twelve tables — rolling back if not.
--
-- The custom-drawers branch this file was originally written for is included
-- there, as the `custom_memories` branch.
--
-- ---------------------------------------------------------------------------
-- WHY THIS IS A TOMBSTONE RATHER THAN A DELETION
-- ---------------------------------------------------------------------------
--
-- Deleting it outright leaves the several documents that referenced it by name
-- pointing at nothing, and leaves anyone holding an older checkout with a
-- dangerous file and no notice. A file that cannot be applied but can be read
-- is the safer end state.
--
-- It was also very nearly missed. On 2026-08-22 the superseded migration was
-- deleted and this twin was left in place, still referenced as a manual step in
-- docs/CUSTOM_DRAWERS_PLAN.md — one dangerous copy removed and an identical one
-- left behind under a different name. Codex caught it. See the entry "Two
-- copies of a tool, and the default one is broken" in
-- wonderland-infrastructure/docs/dev-hygiene.md; this is the third instance
-- this month.
--
-- test/semantic-contract.test.ts now fails if any file other than schema.sql
-- and migrations/semantic-recall-canonical.sql defines this function.
